### ISSUE TITLE
Getting the object property value of object property value in owl-api 

### ISSUE THREAD

**Issue by ridoibm75** [owlcs/owlapi#664]
I'm working with OWL api, to handle my ontology file (.owl) and i'm searching now to get the object property value of object property value !

To clarify: i have an individual/instance which have a list of Object property **#isComposedBy** when i click on one of these values an other object property **#contains** is displayed. AND My objectif is to read out the value of the property #contains

Are there any methods with owl api to achieve my goal, please?

**Comment by ignazio1977** [comment]
Hi, this should help:

        OWLOntology o;
        OWLObjectProperty p1;
        OWLObjectProperty p2;
        Searcher.values(o.axioms(AxiomType.OBJECT_PROPERTY_ASSERTION), p1).peek(System.out::println)
            .forEach(i -> {
                System.out.println("intermediate " + i);
                EntitySearcher.getObjectPropertyValues(i, p2, o).forEach(System.out::println);
            });

**Comment by ridoibm75** [comment]
Thank you iganzio for your answer; 
I used your script and i get an error " can not find symbole " with the keyword "axioms" when i uploaded the package :          import org.semanticweb.owlapi.model.AxiomType;
maybe because i'm using owl 4.0.2 ! Could you please explain more ?

**Comment by ignazio1977** [comment]
The code I've written is for owlapi 5. Very similar methods exist for owlapi 4 but please use 4.3.1 at least. 4.0.2 is very old by now.

**Comment by ridoibm75** [comment]
When i started using owl-api i used 5.1 i had a lot of problems with classpath "java.lang.NoClassDefFoundError" so why i'm using 4.0.2 " this version is much used 

i tried now to reuse 5.1 i added this piece of script in my code every thing look good... but the problem is the same as previous, lack of classes in project, every time i add a jar file to resolve something i get another error and now the error is : 
`java.lang.NoClassDefFoundError: com/google/inject/internal/util/$Maps` and it's the same using 4.3.1

i added the jar file "guice 3.0.0" with sources, and i checked i found that class but i still get the error 
i fear after this error, i'll get another.... 

so please, could you give me all the jar files that i need to avoid these errors of Classnotfound 
or give me another script working with 4.0.2 

PS : i can not work with Maven

**Comment by ignazio1977** [comment]
> PS : i can not work with Maven

I assume there's a good reason for that.

In the releases project (a sibling project of owlapi) there is a dependencypack release for owlapi 4 and one for 5. The jar can be uncompressed to extract all required libraries.

**Comment by ridoibm75** [comment]
i can not find it ! 
could please give me the link.. i need use your piece of script to solve my problem 
thanks

**Comment by ignazio1977** [comment]
https://github.com/owlcs/releases/tree/master/owlapi/5

**Comment by ridoibm75** [comment]
thank you very much Ignazio, it work good now
let's return to my problem case, i tried your script but i need some clarifications
what do you want to say by Prop 1 and prop 2, is it prop 2 Included in prop1 ? 

to clarifiy more : 
let's suposse that my individual = text  
this text contain an object property : #isComposed 
so the value of this property = sentence 
now when i click on this sentence another property is displayed : #contains 
it means this sentences contains some words
which means words = the value of the property #contains

i need to get the words for each text

**Comment by ridoibm75** [comment]
this is my code 
```
    public void loadOntology () throws OWLOntologyCreationException  {
                                       
                manager = OWLManager.createOWLOntologyManager(); 
                myOntology = manager.loadOntology(fileURI);
                ontologyIRI = IRI.create("http://www.limics.fr/ontologies/ontoparon"); 
                df = manager.getOWLDataFactory();
                System.out.println("Loading Ontology...\n"  + myOntology);
                System.out.println("-----------------------");     
                
                for (OWLClass cls : myOntology.getClassesInSignature()) {                            
                    
                    if  (cls.getIRI().getFragment().equals("Doc")){
                        System.out.println("My class is : " + cls.getIRI().getShortForm());
                        System.out.println("The IRI of my class is : "+ cls);                        
                        System.out.println("-----------------------");
                        
                        OWLReasoner reasoner = reasonerFactory.createReasoner(myOntology);
                        NodeSet<OWLNamedIndividual> instances = reasoner.getInstances(cls, true);
                        System.out.println("The Individuals of my class : ");
                    
                        for (OWLNamedIndividual txt : instances.getFlattened()) {
                            System.out.println("TEXTE NUMBER : " + txt.getIRI().getFragment());
                         
                            isComposedBy = df.getOWLObjectProperty(IRI.create(ontologyIRI + "#"+"isComposedBy"));
                            contains = df.getOWLObjectProperty(IRI.create(ontologyIRI + "#"+"contains"));
                            Set<OWLNamedIndividual> sentence = reasoner.getObjectPropertyValues(txt, isComposedBy).getFlattened();
                            System.out.println("SENTENCES OF THIS TEXT : " + sentence);                             
                                                
                            Searcher.values(myOntology.axioms(AxiomType.OBJECT_PROPERTY_ASSERTION), isComposedBy).peek(System.out::println)
                            .forEach(i -> {
                            System.out.println("intermediate " + i);
                            EntitySearcher.getObjectPropertyValues(i, contains, myOntology).forEach(System.out::println);
                                          });                        
                        }  
                    }                   
                }                              
    }
```

**Comment by ignazio1977** [comment]
I've updated my previous comment to clarify which property is which.

**Comment by ridoibm75** [comment]
Thank you inganzio, your piece of code give me nearly what i want, : sentences (value of the property #isComposedBy) and theirs words (value of the property #contains) 

in fact it miss just something to get really what i want, i tried to modify and i think i have a problem of **Display** 
because i want to to get something like this : 
TEXT NUMBER : ........ 
SENTECES : <........>,<........>,<...>.....
WORDS : .................
TEXT NUMBER : ........ 
SENTECES : <........>,<........>,<...>.....
WORDS : .................
TEXT NUMBER : ........ 
SENTECES : <........>,<........>,<...>.....
WORDS : ..................

Now i need just to add something to the code to **get the words just under the sentences**, **because in final i want to display every text with theirs words** and i do not care which sentence depends these words
i wish that it's clear ! 

Thank you so much in advance

**Comment by ridoibm75** [comment]
thank you for your answer, in fact your piece of code give me nearly what i want 
i need to precise that when i execute your code 
give me with **every text** all the sentences with theirs words (it repeat) 
I want each text with its own sentences and words 

PS : my code (without your piece) every text with their sentences. i'm searching just to add a lin of words 
something like this : 

TEXT NUMBER : ........
SENTECES : <........>,<........>,<...>.....
WORDS : .................

TEXT NUMBER : ........
SENTECES : <........>,<........>,<...>.....
WORDS : .................

TEXT NUMBER : ........
SENTECES : <........>,<........>,<...>.....
WORDS : ..................

**Comment by ridoibm75** [comment]
I modifed your solution and i get what i want 
```
      for (OWLNamedIndividual m : sentence ) {    
                   Searcher.values(myOntology.axioms(AxiomType.OBJECT_PROPERTY_ASSERTION), isComposedBy).peek(System.out::println);                                        
                   System.out.println("intermediate " + m);
                   EntitySearcher.getObjectPropertyValues(m, contains, myOntology) .forEach (System.out::println);                                                                 
 }
```
thank you Ignazio :)
