### ISSUE TITLE
error loading text/turtle file

### ISSUE THREAD

**Issue by nimonika** [owlcs/owlapi#484]
I am trying to load the ontology `http://mex.aksw.org/mex-core` using the API. When trying to access the URI through the web browser, its asks to save a turtle file. While trying to load the document through the API, I get a ```Exception in thread "main" java.lang.NoSuchMethodError: org.openrdf.rio.ParserConfig.addNonFatalError(Lorg/openrdf/rio/RioSetting;)V```error and the rest of my process terminates. I tried handlng the exception in my own code, but it appears that this would not work because of the origins of the error. is there any other method that can help me load the ontology?

**Comment by ignazio1977** [comment]
Do you have a version of Sesame on the classpath that does not match the one coming with OWLAPI?

OWLAPI 4 uses version 2.7 (2.7.12 I think). It might not be compatible with other versions.

**Comment by nimonika** [comment]
This seems to be the case.

**Comment by ansell** [comment]
Newer versions of Sesame, such as 2.8 and 4.0, use RDF-1.1, which will not work with the RDF-1.0 based OWLAPI-4 series at this point in time.
